INSERT INTO checkpoints (id, name, description, created_by, instructor_id, validity_period, total_gradepoints, achieved_gradepoints)
VALUES
    ('1','ObjectOrientedProgramming','This is the description text of This course','1', '13', '3Years', 100, 85),
    ('2','Data Structure','This is the description text of This course','1', '13', '3Years', 100, 85),
    ('3','Artificial Intelligence','This is the description text of This course','1', '14', '3Years', 100, 85),
    ('4','Entrepreneurship','This is the description text of This course','1', '14', '3Years', 100, 85),
    ('5','Technical and Report Writing','This is the description text of This course','1', '14', '3Years', 100, 85),
    ('6','Programming Fundamentals','This is the description text of This course','2', '15', '3Years', 100, 85),
    ('7','Software Engineering','This is the description text of This course','2', '14', '3Years', 100, 85),
    ('8','Web Development','This is the description text of This course','2', '11', '3Years', 100, 85),
    ('9','Mobile Application Development','This is the description text of This course','1', '13', '3Years', 100, 85),
    ('10','Cloud Computing','This is the description text of This course','3', '11', '3Years', 100, 85),
    ('11','Financial Accounting','This is the description text of This course','4', '11', '3Years', 100, 85),
    ('12','Introduction to psychology','This is the description text of This course','4', '12', '3Years', 100, 85),
    ('13','DevOps','This is the description text of This course','1', '13', '3Years', 100, 85),
    ('14','Database Management','This is the description text of This course','2', '15', '3Years', 100, 85),
    ('15','Information Technology','This is the description text of This course','2', '16', '3Years', 100, 85),
    ('16','Telecommunications','This is the description text of This course','5', '16', '3Years', 100, 85),
    ('17','Computer Networks','This is the description text of This course','6', '17', '3Years', 100, 85),
    ('18','Operating Systems','This is the description text of This course','7', '17', '3Years', 100, 85),
    ('19','Human Computer Interaction','This is the description text of This course','7', '18', '3Years', 100, 85),
    ('20','Principles of UI & UX','This is the description text of This course','5', '19', '3Years', 100, 85),
    ('21','Backend Development','This is the description text of This course','8', '11', '3Years', 100, 85),
    ('22','Visual Programming','This is the description text of This course','9', '11', '3Years', 100, 85),
    ('23','Blockchain Development','This is the description text of This course','4', '12', '3Years', 100, 85),
    ('24','Soft Skills','This is the description text of This course','3', '14', '3Years', 100, 85),
    ('25','Data Warehousing and Mining','This is the description text of This course','1', '15', '3Years', 100, 85);
